=== downloard/Uyoo/resources/settings.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
<xs:element name="settings">
    
    <xs:complexType>
      <xs:sequence>     
        <xs:element name="files">
          <xs:complexType>
            <xs:sequence>
                        
              <xs:element maxOccurs="unbounded" name="f">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string" />
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      
      	<xs:element name="pattern">
          <xs:complexType>
            <xs:sequence>
                        
              <xs:element maxOccurs="unbounded" name="p">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="name" type="xs:string" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
        <xs:element name="filter">
          <xs:complexType>
            <xs:sequence>
              
              <xs:element maxOccurs="unbounded" name="f">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="name" type="xs:string" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== downloard/Uyoo/settings.xml
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="settings.xsd">
	<pattern>
		<p name="STF">^&lt;(.+)&gt;(.+?):.*\[(.+?):(.+? )(.*)\]:(.+)$</p>
		<p name="Test">^(.*)$</p>
	</pattern>
	<filter>
		<f name="Empty"></f>
		<f name="Error">2:Error</f>
		<f name="SDManager">3:CSDManager</f>
	</filter>
</settings>
